### ISSUE TITLE
Doesn't compile on M1/2

### ISSUE THREAD

**Issue by sidan5** [renaudjenny/SwiftClockUI#20]

**Comment by renaudjenny** [comment]
Hi @sidan5 , I've just tested on my M1 MacBook Pro and it compiles without any issue in **Xcode 14.3.1**.
Could you please let me know which version of Xcode you're using and if you're not using Xcode, the command line you've executed?

<img width="2197" alt="image" src="https://github.com/renaudjenny/SwiftClockUI/assets/2297556/545dad74-81e0-4f59-b7d0-5b7c53a1040a">

Cheers.

**Comment by renaudjenny** [comment]
Hi @sidan5 , I'm sorry, but I can't really help if you're not providing more info.
I'm happy to have a look at your problem, I will let this ticket opened for a couple of days but will close it if there is no response.
Thank you.

**Comment by sidan5** [comment]
@renaudjenny Thank you for your prompt reply. I'll try with a demo project and let you know.

**Comment by sidan5** [comment]
@renaudjenny Might be something specifically in my project. Closing for now. Thank you for your support!

**Comment by renaudjenny** [comment]
@sidan5 no problem. Let me know if I can help further, happy to see this library could be interesting for you ☺️.
